# 七傳說 · 上線前全檢報告（修訂版 v2）

> 日期：2026-09-23（v2 修訂 17:2x）｜ 引擎：Godot 4.7.2 stable ｜ 工程：`D:\七傳說\game`
> 範圍：代碼審查 · 安全審計 · QA 回歸（65 腳本）· 打包交付
>
> **v2 修訂摘要**：① 打包時間與產物雜湊更新為最終包；② §3.1 的 P0（ch1_l05/l06）**已修復並回歸驗證**；
> ③ §4.4「上架就緒缺口」因**用戶裁定「代碼不上線」而移出範圍**；④ 新增 §3.5 兩條 v2 新發現。

---

## 〇、結論速覽

| 項目 | 結果 |
|---|---|
| 打包 | ✅ 成功。`D:\七傳說\game\build\七傳說.exe`（128,723,832 B，2026-09-23 17:04:46） |
| 導出包冒煙 | ✅ `七傳說.exe --smoke` → **端到端 0 項失敗**，exit 0；第一關 ch1_l01 刷出 25 敵、掉落/結算/存讀檔全通 |
| 代碼審查 | ✅ 85 腳本 / 20431 行全部可解析；無空吞異常；無非法節點聲明 |
| 安全審計 | ✅ **零網絡能力 · 零命令執行 · 零硬編碼密鑰**；用戶內容層為唯一外部輸入面 |
| QA 回歸 | ✅ 65 腳本：原 3 類紅燈中，**P0 已修**；剩 6 腳本 9 條斷言為**斷言過期 / 風格門禁**、5 腳本為**框架誤報**（皆非阻塞） |
| 上線阻塞 | ✅ **無**。原 P0「ch1_l05 / ch1_l06 不可玩」已修復（§3.1） |

### 〇.1 本次範圍裁定（依用戶指令）

| 用戶指令 | 影響 |
|---|---|
| **代碼不上線** | 免除上架元數據、代碼簽名、PCK 加密、存檔防篡改。原 §4.4 整節移出範圍 |
| **目前只需要第一關運行** | 驗收線 = `ch1_l01` 可玩。**已達成**（冒煙 0 項失敗） |

> 這兩條同時關閉了記憶庫中長期掛著的衝突項：「平台 PC / Steam」vs 任務清單 D7「純自玩、不上線」——
> 現以用戶口頭裁定為準：**純本地自玩**。

---

## 一、打包交付（可運行地址）

```
D:\七傳說\game\build\七傳說.exe
```

| 項 | 值 |
|---|---|
| 大小 | 128,723,832 bytes（122.8 MB） |
| 導出時間 | 2026-09-23 **17:04:46**（最終包，含 P0 修復） |
| MD5 | `1078e026f6da49b7129b0e216e0f73fb` |
| PE 頭 | ✅ `MZ` 校驗通過 |

**舊包與存檔均已備份（非刪除）**，位於 `game\build\_prev\`：

| 目錄 | 內容 |
|---|---|
| `20260923-165517\` | 第一次打包的 exe（P0 修復**前**） |
| `20260923-165814\` | 被清除的存檔（4 檔：`slot_00.json` / `slot_07.json` / `slot_07.json.bak1` / `slot_07.corrupt_1790152792`） |
| `20260923-170328\` | 第二次打包的 exe（P0 修復**前**）+ `appdata_saves` + `appdata_content` |

直接雙擊即可運行；本報告撰寫時已啟動一次遊戲窗口。

### 1.1 ⚠️ 打包踩坑：`APPDATA` 為空會「靜默繞過清檔 + 導出失敗」

本 shell 的 `APPDATA` 是**空串**，Godot 於是把數據目錄解析成**相對路徑** `./Godot/`，造成兩個後果：

1. **導出直接失敗**——Godot 去 `./Godot/export_templates/4.7.2.stable/` 找模板，而模板實際在
   `%APPDATA%\Godot\export_templates\4.7.2.stable\`（109 MB 在位）。報錯：
   `在預期路徑處未找到導出模板：...windows_release_x86_64.exe`
2. **「每次打包清數據」鐵律被靜默繞過**——`package_demo.py` 的兩個掃描根都落空，
   真實存檔（`%APPDATA%\Godot\app_userdata\七傳說\saves\`）一個都沒清，腳本卻只印「跳過 不存在」。

**正確調用方式**（本次採用）：

```bash
cd D:/七傳說/game
APPDATA='C:\Users\11265\AppData\Roaming' python tools/package_demo.py --backup
```

> 建議：在 `package_demo.py` 裡加一條前置校驗——`APPDATA` 為空時**直接中止並提示**，
> 而不是靜默產出「沒清乾淨」的包。目前這個坑對使用者是完全不可見的。

---

## 二、代碼審查

| 檢查項 | 結果 |
|---|---|
| GDScript 解析（`parse_all` 全項目預檢） | ✅ 全部可解析 |
| 空吞異常（裸 `pass`） | ✅ 0 處 |
| `.tscn` 非法節點聲明（漏 `type=` / `instance=`） | ✅ 0 處（歷史上「敵人無碰撞體」那類靜默丟失已清零） |
| 危險系統調用（`OS.execute` / `shell_open` / `create_process`） | ✅ 0 處 |
| 遞迴刪除（`remove_absolute` / `rmdir`） | ✅ 0 處 |
| 硬編碼密鑰 / 口令 / token | ✅ 0 處 |

**規模與熱點**（85 遊戲腳本 / 20431 行）：

| 檔案 | 行數 | 備註 |
|---|---|---|
| `scripts/core/game_constants.gd` | 1585 | 常量總表，屬「數據字典」性質，可接受 |
| `scripts/run/level_scene.gd` | 1473 | 關卡裝配 + 生成 + 事件接線，**職責偏多** |
| `scripts/player/player_controller.gd` | 1230 | |
| `scripts/enemies/enemy_base.gd` | 1182 | |
| `scripts/autoload/config_loader.gd` | 1124 | 12 張表的加載 + 校驗，分層清楚 |

**做得好的地方**（不是客套，是實測）：

- **數據層防禦完整**：JSON 解析錯誤全部收口到 `load_errors` 並 `push_warning`，不靜默；
  `_register()` 拒絕空 id 與重複 id；`_validate()` 逐條調用資源自帶校驗；
  `_to_slot()` / `_to_slot_array()` 等弱類型轉換統一夾緊（`clampi`），髒數據進不來。
- **存檔層**：SHA-256 信封校驗 + 原子寫（`.tmp` → 替換）+ 3 份備份輪轉 + 損壞檔隔離（改名不刪）；
  且**主檔損壞回滾到備份後會立刻回寫主檔**——否則選檔界面會把槽位顯示成「空檔」，
  玩家以為存檔丟了。這個細節修得很對。
- **啟動分流**：`--verify` / `--smoke` / 正常啟動三態共用一個入口，導出包內可自測。
  這是「導出後才發現資源沒打進包」這類問題的根治手段。

**待改進**：

- `level_scene.gd` 1473 行、承擔裝配/生成/事件三類職責，建議後續拆分（非阻塞）。
- `game_constants.gd` 的怪物數值**註釋塊已過期**（見 §3.5）。

---

## 三、QA 回歸（65 腳本 / ~134s）

回歸驅動 `game/tools/run_regression.py` 自動發現全部 `verify_*.tscn` + `self_check`，
使用隔離 `APPDATA`（避免並發搶 `saves/` 造成假紅）。結果按性質分三類。

### 3.1 ✅ 真 bug — P0「ch1_l05 / ch1_l06 完全不可玩」**已修復**

**修復前症狀**

```
ERROR: [LevelGenerator] 手繪地圖 'ch1_l05' 非法：有 41 個雜兵標記 'm'，超過本關預算 Σcount_max=34
ERROR: [LevelGenerator] 手繪地圖 'ch1_l06' 非法：有 32 個雜兵標記 'm'，超過本關預算 Σcount_max=20
[LevelGenerator] 手繪地圖 'ch1_l05' 有 1 處非法，已放棄生成
```

- 手繪地圖的 `'m'`（雜兵）數量**超過該關 `monster_entries` 的 `Σcount_max` 預算**，
  校驗器判定非法 → `_generate_authored()` **整體放棄生成**，返回 `player_spawn = (-1,-1)`。
- 連鎖後果：出生點不存在 → 4 連通可達 **0 / 769 格**（l05）、**0 / 960 格**（l06）；
  怪物 0、BOSS 錨點 `(-1,-1)`。**第一章第 5、6 關（含章末 BOSS 關）整關打不開。**
- **重要澄清**：關卡**原始數據是對的**——`@` 出生點落在可走地面、四鄰可走、全圖連通。
  問題純粹是「手繪標記數 vs 關卡預算」這條**數值約束**不匹配，不是畫錯圖。

**根因**：`Σcount_max`（34 / 21）與聲明的 `total_monster_budget`（62 / 66）自相矛盾。
預算曲線斷裂：

| 關 | l01 | l02 | l03 | l04 | l05 | l06 |
|---|---|---|---|---|---|---|
| `total_monster_budget`（步驟 9 設計曲線） | 40 | 50 | 55 | 58 | **62** | **66** |
| `Σcount_max`（**修復前**） | 40 | 51 | 44 | 43 | **34** ✗ | **21** ✗ |
| `Σcount_max`（**修復後**） | 40 | 51 | 44 | 43 | **62** ✅ | **66** ✅ |

**採用的修法**：**選項 (b) 提預算** —— 把 `count_max` 抬到與 `total_monster_budget` 一致。

```jsonc
// ch1_l05（Σcount_max 34 → 62）
{ "monster_id": "skeleton_warrior", "count_min": 13, "count_max": 37, ... },
{ "monster_id": "brute_butcher",   "count_min":  2, "count_max":  5, ... },
{ "monster_id": "slime_acid",      "count_min":  7, "count_max": 20, ... }

// ch1_l06（Σcount_max 20 → 65；+ BOSS 1 = 66）
{ "monster_id": "skeleton_warrior", "count_min": 13, "count_max": 56, ... },
{ "monster_id": "wraith_frost",     "count_min":  2, "count_max":  9, ... },
{ "monster_id": "boss_bone_tyrant", "count_min":  1, "count_max":  1, "is_boss": true }
```

> **關鍵性質**：手繪模式下 `count_max` **不參與刷怪**（`_generate_authored()` 只按 `'m'` / `'e'` / `'B'`
> 標記數量生成）。⇒ 本次修改**不改變任何實際刷怪數**，純粹是修復校驗閘門。
> 之所以選 (b) 而非 (a)：`total_monster_budget` 是**權威設計字段**，被 `verify_metrics`、
> `verify_polish9x` 按步驟 9 曲線斷言；改它會連環破壞平衡斷言。改 `Σcount_max` 是零副作用解。

**修復後實證**（`verify_level_gen` 直跑輸出）

```
[OK]   手繪逐格統計 = ... ch1_l05 26×44 地769/墙357/障18 m41 e3 p3;
                       ch1_l06 48×36 地960/墙748/障20 m32 e4 p3 B
[OK]   ch1_l06 的 BOSS 錨點 = 手繪 'B' 所在格 (24,5)
[OK]   ch1_l06 的 BOSS 錨點在地面且遠離出生（26.0 格）
[OK]   連通性：手繪關卡可行走格 100% 從 '@' 可達且四類錨點可達
       （ch1_l01 705/705, ch1_l02 626/626, ch1_l05 769/769, ch1_l06 960/960）
===== 結果：0 項失敗 =====
```

**回歸翻紅 → 全綠對照**：

| 腳本 | 修復前 | 修復後 |
|---|---|---|
| `verify_level_gen` | 6 項失敗 | **0 項失敗** |
| `verify_terrain8b` | 6 項失敗 | **0 項失敗** |
| `verify_boss_awaken8c` | 2 項失敗 | **0 項失敗** |

**修改確實進了包**（雙重取證）：① 三版 exe 的 MD5 兩兩不同（同字節數只是 PCK 對齊填充）；
② 直接在 exe 二進制內搜到 `count_max": 56` 與 `count_max": 37`。

**⚠️ 一併澄清一條「偽 bug」**：修復前日誌裡有

```
WARNING: [Level] ch1_l06 目標是擊殺 BOSS，但 monster_entries 裡沒有任何 is_boss=true 的條目
```

`ch1_l06` **確實已配** `boss_id = "boss_bone_tyrant"`，且 `monster_entries` 中該條目**確實有**
`is_boss: true`。這條 WARNING 是**生成被中止的症狀**（`_boss_total` 為 0），不是數據缺陷；
但它的措辭把責任指向 `monster_entries`，**會把排查方向帶偏**（本輪確實一度帶偏）。
建議把措辭改成「本關 BOSS 未刷出（生成器可能已放棄生成）」。

**P2 — 手柄用不了藥水**（未修，非阻塞）

`verify_player`：`全部 16 個動作均有鍵 + 手柄雙映射` 失敗。
`project.godot` 中 `consume_1`(Q) / `consume_2`(R) **只有鍵盤事件、沒有手柄事件**，
手柄玩家無法使用消耗品。其餘 14 個動作雙映射齊全。

### 3.2 🟡 斷言過期（實現已改，測試沒跟上 —— 不改玩法，只需同步）

| 測試 | 斷言寫死 | 實際 | 來源 |
|---|---|---|---|
| `verify_fix85` | 技能 **8** | **12**（`skills.json` 實測 12，導出包 ConfigLoader 亦報 12） | 步驟 3 加了 4 個職業技能 |
| `verify_skill_panel` | `save_version == 3` | `SAVE_VERSION = 4` | 步驟 8A 消耗品入檔，3→4 |
| `self_check` / `verify_settings` | 音效註冊表 **9** 條 | **10** 條（多 `boss_roar`） | 步驟 8E 加開戰吼 |
| `self_check` | 怪物 L20 HP ≈ **11635** / DMG ≈ **237.83** | **4404.2 / 94.12** | 步驟 9 平衡放緩（見 §3.5） |

> 這批失敗會讓回歸長期掛紅，進而掩蓋真問題（狼來了效應），建議優先同步。

### 3.3 🟠 框架誤報（腳本其實**全過**）

`run_regression.py` 的結果行判定只認三種寫法：

```python
if "项失败" in line or "全部通过（" in line or "项未通过" in line:   # run_regression.py:166
```

而下列腳本輸出的是**繁體**「全部通過」或「`N 通過 / 0 失敗`」格式，於是被判 `NO-RESULT`（＝空轉失敗）。
**注意**：它用簡體「项」，而專案腳本混用繁簡，所以連「項失敗」也認不出。

| 腳本 | 實際末行 | 判定 |
|---|---|---|
| `verify_class_select` | `===== 角色选择面板實測 結束：全部通過 =====` | ❌ 誤報 |
| `verify_consumable` | `===== 結果：27 通過 / 0 失敗 =====` | ❌ 誤報 |
| `verify_equip_panel` | `===== 装备系统页实测 结束：全部通过 =====` | ❌ 誤報 |
| `verify_hud` | `===== 步骤 6 实测 结束：全部通过 =====` | ❌ 誤報 |
| `verify_panel_unify` | `===== 统一视觉实测 结束：全部通过 =====` | ❌ 誤報 |

> 這是**測試基礎設施**的缺陷，不是遊戲缺陷。建議把判定改成
> 「正則匹配 `N\s*(项|項)失敗|N\s*(项|項)未通過|全部通過|全部通过|N\s*通過\s*/\s*M\s*失敗`」。

### 3.4 🔵 風格門禁

`verify_choice_panel`：`scripts/ui/choice_panel.gd` L693 / L704 出現 2 處**裸 `Color(...)` 字面量**。
兩處 alpha 皆為 0（純透明佔位），無視覺影響，但違反「顏色統一走 48 色板」的項目鐵律。

### 3.5 🆕 v2 新發現（本輪追加）

**① `game_constants.gd` 怪物數值註釋塊已過期（P3，純文檔，但會誤導人）**

`scripts/core/game_constants.gd:462-476` 的註釋仍寫：

```
##   Monster_HP(L)  = 100.7 × 1.284^(L-1)
##   Monster_DMG(L) =  5.61 × 1.218^(L-1)
##   L20 普通怪：HP ≈ 11,635 / DMG ≈ 237.83
```

而其**下方第 478 / 480 行的常量**已是 `1.22` / `1.16`（行內註釋標明「9.x 調優」）。
實算：**L20 HP = 4404.2、DMG = 94.12**（與註釋相差 2.6 倍 / 2.5 倍）。

- 這正是 `self_check` 那兩條斷言的來源——它照著過期註釋寫死了期望值。
- ⇒ 修法：把 §462-476 的公式與錨點更新為 `1.22` / `1.16` 與 `4404.2 / 94.12`，
  再同步 `self_check.gd:115-120`。**注意**：這是一組「配套斷言」，HP/DMG 必須一起改。

**② `ch1_l02` 預算有 1 點殘差（P4，非阻塞）**

| 關 | `'m'` 實畫 | `Σcount_max`(非BOSS) | `total_monster_budget` | 是否卡校驗 |
|---|---|---|---|---|
| ch1_l02 | 48 | **51** | **50** | ✅ 不卡（48 ≤ 51） |

校驗閘門只看 `'m'` 數是否**超過** `Σcount_max`，所以 l02 能正常生成；
但 `Σcount_max` 比聲明預算多 1，屬**殘餘不一致**。因 `total_monster_budget=50` 受步驟 9
曲線斷言保護**不可動**，若要抹平應把 l02 的 `Σcount_max` 從 51 降到 50（手繪模式零副作用）。
優先級低，不影響任何可玩性。

---

## 四、安全審計

單機離線遊戲的攻擊面本就極小，實測結論如下。

### 4.1 ✅ 攻擊面消除（正面結論）

| 維度 | 實測 | 意義 |
|---|---|---|
| 網絡能力 | **0 處** `HTTPRequest` / `HTTPClient` / `WebSocket` / `TCP` / `UDP` / URL | 無遠程攻擊面，單機最優解 |
| 命令執行 | **0 處** `OS.execute` / `OS.shell_open` / `OS.create_process` | 無任意代碼執行面 |
| 憑證洩漏 | **0 處** 硬編碼 password / secret / token / api_key | 無密鑰可被提取 |
| 破壞性文件操作 | **0 處** 遞迴刪除；存檔刪除僅限 `_all_paths_for_slot()` 白名單 | 不會誤刪用戶文件 |

### 4.2 🟡 用戶內容層（唯一外部輸入面）

`user://content/{characters,fx,tilesets,levels,icons,music,ui}/` 提供「不改代碼換素材」，
是設計亮點，也是唯一的不可信輸入入口。

- **做對的**：加載前 `ensure_user_dirs()` 建目錄並打印**絕對路徑**給用戶；
  `res://` 走 `ResourceLoader`、`user://` 走 `FileAccess`（兩者語義不可互換，這裡分得很清）。
- **可加固**：`ContentPaths.user_path(klass, relative)` **未對 `relative` 做 `..` 淨化**，
  `class_dir(...).path_join(biome)` 同理。目前所有調用方的 `relative` 都來自硬編碼或包內數據，
  **現實不可利用**；但一旦未來把關卡 id / biome 暴露成用戶可填字段，就會變成路徑穿越。
  建議加一行 `relative.simplify_path()` + 前綴校驗（縱深防禦，成本極低）。

### 4.3 ✅ 導出配置（單機口徑下無問題）

| 配置 | 現值 | 評價 |
|---|---|---|
| `script_export_mode` | `2`（壓縮二進制 token） | ✅ 源碼非明文 |
| `encrypt_pck` / `encrypt_directory` | `false` / `false` | ✅ **單機自玩口徑下可接受**（PCK 可解包，但無商業機密外洩風險） |
| 存檔 `SHA-256` | 有 | ✅ 只防**意外損壞**，不防人為改檔——單機無排行榜，無影響 |

### 4.4 ~~🔴 上架就緒缺口~~ → **已移出範圍**

> **作廢理由**：用戶裁定「**代碼不上線**」。`export_presets.cfg` 中
> `application/icon` / `file_version` / `product_version` / `company_name` / `copyright` 全空、
> `codesign/enable=false` 等項，**僅在發行（Steam）語境下才是缺口**；
> 純本地自玩時：exe 無圖標、屬性頁空白、SmartScreen 提示「未知發布者」——**均不影響運行**。
> 若日後改變主意要上線，再回看本節即可。

---

## 五、待你拍板（僅剩可選項）

**已完成、無需拍板**：

- ✅ ch1_l05 / ch1_l06 預算不一致 → 已按「(b) 提預算」修復並回歸驗證
- ✅ 第一關可運行 → 已交付 `build\七傳說.exe`

**以下三項皆為非阻塞可選，做了不影響玩法、不做也不影響第一關運行**：

1. **同步 §3.2 的過期斷言**（含 §3.5① 的註釋塊 + `self_check` 配套值）——純測試/文檔維護，
   但做了能讓回歸重新「全綠可信」，消除狼來了效應。**推薦做**。
2. **修 §3.3 回歸框架的結果行判定**——不修的話，回歸會**永久**掛 5 個假紅。
   這是修「誤報偵測器」而非放寬標準，風險極低。**推薦做**。
3. **§3.1 手柄 `consume_1/2` 補手柄映射**（P2）與 **§3.4 `choice_panel` 兩處裸 `Color`**（風格門禁）——
   前者手柄玩家受影響，後者純規範。

---

## 附：本次全檢用到的指令（可復現）

```bash
# 1) QA 回歸（隔離 APPDATA，避免假紅）
cd D:/七傳說/game && python tools/run_regression.py

# 2) 單跑某個 verify（快速定位）
GODOT="C:/Users/11265/AppData/Local/Microsoft/WinGet/Packages/GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe/Godot_v4.7.2-stable_win64_console.exe"
APPDATA='C:\Users\11265\AppData\Roaming' "$GODOT" --headless --path . res://tools/verify_level_gen.tscn

# 3) 打包（必須帶 APPDATA，否則導出失敗 + 漏清存檔）
cd D:/七傳說/game && APPDATA='C:\Users\11265\AppData\Roaming' python tools/package_demo.py --backup

# 4) 導出包端到端冒煙
cd D:/七傳說/game/build && APPDATA='C:\Users\11265\AppData\Roaming' ./七傳說.exe --smoke
```
